dist: bionic
sudo: required

# Enable C++ support
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - gcc-7
      - cmake
      - make
      - build-essential
      - libglew-dev
      - nvidia-opencl-dev
      - opencl-headers
      - libfreeimage-dev
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev 
      - libassimp-dev
      - libglfw3-dev

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1 -j
